---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Abnormal
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/abnormal.jpeg"
  category: email
  resourceGroups:
    - Abnormal
  description: "Abnormal Security Events via API Integration"
  displayName: "Abnormal Security Events"
  parameters:
    - name: token
      description: "API Token"
      dataType: string
      defaultValue: ""
      sensitive: true
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Abnormal
  secret:
    AbnormalSecret:
      secretKey: "{{ .UserInput.token }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - AbnormalSecurity-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: AbnormalSecurity-Adjustments
spec:
  type: parser
  local: AbnormalSecurity_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"

