---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Duo
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/duo.png"
  category: office
  resourceGroups:
    - CiscoDuo
  description: "Cisco Duo Events via Admin API Integration"
  displayName: "Cisco Duo Admin API"
  parameters:
    - name: integrationKey
      description: "Admin API Integration key"
      dataType: string
      defaultValue: ""
    - name: secretKey
      description: "Admin API Secret key"
      dataType: string
      defaultValue: ""
      sensitive: true
    - name: apiHostname
      description: "Admin API hostname"
      dataType: string
      defaultValue: ""
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Duo
  config:
    Duo:
      integrationKey: "{{ .UserInput.integrationKey }}"
      apiHostname: "{{ .UserInput.apiHostname }}"
  secret:
    DuoSecret:
      secretKey: "{{ .UserInput.secretKey }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - CiscoDuo-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: CiscoDuo-Adjustments
spec:
  type: parser
  local: CiscoDuo_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
