---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Darktrace
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/darktrace.png"
  category: email
  resourceGroups:
    - Darktrace
  description: "Darktrace Threat Visualizer API Integration"
  displayName: "Darktrace Threats"
  parameters:
    - name: url
      description: "URL"
      dataType: string
      defaultValue: ""
    - name: publicToken
      description: "Public Token"
      dataType: string
      defaultValue: ""
    - name: privateToken
      description: "Private Token"
      dataType: string
      defaultValue: ""
      sensitive: true
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Darktrace
  config:
    Darktrace:
      url: "{{ .UserInput.url }}"
      publicToken: "{{ .UserInput.publicToken }}"
  secret:
    DarktraceSecret:
      privateToken: "{{ .UserInput.privateToken }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - Darktrace-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: Darktrace-Adjustments
spec:
  type: parser
  local: Darktrace_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"

