---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: CrowdStrike_Falcon
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/crowdstrike.png"
  category: endpoint
  resourceGroups:
    - CrowdStrike
  description: "CrowdStrike Falcon XDR Incidents"
  displayName: "CrowdStrike Falcon"
  parameters:
    - name: baseURL
      description: "API Base URL"
      dataType: string
      defaultValue: ""
    - name: clientID
      description: "Client ID"
      dataType: string
      defaultValue: ""
    - name: clientSecret
      description: "Client Secret"
      dataType: string
      defaultValue: ""
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Falcon
  config:
    Falcon:
      baseURL: "{{ .UserInput.baseURL }}"
      clientID: "{{ .UserInput.clientID }}"
  secret:
    FalconSecret:
      clientSecret: "{{ .UserInput.clientSecret }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - CSFalcon-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: CSFalcon-Adjustments
spec:
  type: parser
  local: CSFalcon_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
