---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: FortiGateFWLog
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/fortinet-via-syslog-sq.png"
  category: onpremise
  resourceGroups:
    - Fortigate
  description: "FortiGate Firewall Events via Syslog"
  displayName: "FortiGate NGFW Syslog"
  parameters:
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: FortiGate-FWLog
spec:
  type: parser
  local: FortiGate_FWLog
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - FortiGate-FWLog
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: SyslogRouter
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
