---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Office365Resource
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/office365-blue.png"
  category: office
  description: "Office365 resource watch"
  displayName: "Office365 Resource Watch"
  adminConsent: true  
  parameters:
    - name: adminConsentEmail
      description: "admin email address"
      dataType: string
      defaultValue: ""
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Office365ResourceWatch
  adminConsent: "{{ .UserInput.adminConsentEmail }}"
