---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Okta
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/okta.png"
  category: business
  resourceGroups:
    - Okta
  description: "Okta Events via API Integration"
  displayName: "Okta Events"
  parameters:
    - name: domain
      description: "Okta Domain"
      dataType: string
      defaultValue: ""
    - name: token
      description: "API Token"
      dataType: string
      defaultValue: ""
      sensitive: true
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Okta
  config:
    Okta:
      domain: "{{ .UserInput.domain }}"
  secret:
    OktaSecret:
      token: "{{ .UserInput.token }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - Okta-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: Okta-Adjustments
spec:
  type: parser
  local: Okta_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
