---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: Proofpoint
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/proofpoint.png"
  category: email
  description: "Proofpoint Events via API Integration"
  displayName: "Proofpoint Events"
  parameters:
    - name: principal
      description: "Principal"
      dataType: string
      defaultValue: ""
    - name: secret
      description: "Secret"
      dataType: string
      defaultValue: ""
---
apiVersion: application.ingext.io/v1
kind: Integration
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: Proofpoint
  config:
    Proofpoint:
      principal: "{{ .UserInput.principal }}"
  secret:
    ProofpointSecret:
      secret: "{{ .UserInput.secret }}"
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: plugin
  format: json
  router: "{{ .Application }}-{{ .AppInstance }}"
  config:
    plugin:
      integration: "{{ .Application }}-{{ .AppInstance }}"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - Proofpoint-Adjustments
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: "{{ .Application }}-{{ .AppInstance }}"
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: Proofpoint-Adjustments
spec:
  type: parser
  local: Proofpoint_Adjustments
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"

