---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: SentinelOne_Syslog
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/s1-via-syslog-sq.png"
  category: endpoint
  description: "Alerts / Events from SentinelOne Syslog integration via Syslog"
  displayName: "Fortigate NGFW Syslog"
  parameters:
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: SentinelOne-Syslog
spec:
  type: parser
  local: SentinelOne_Syslog
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - SentinelOne-Syslog
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: SyslogRouter
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
