---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: CloudSyslog
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/fluency-collector-via-syslog-sq.png"
  category: system
  description: "Syslog import on AWS Cloud"
  displayName: "Cloud Syslog"
  parameters:
    - name: Region
      description: "AWS Region"
      dataType: string
      defaultValue: ""
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: SyslogRouter
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: CloudSyslogTimestampAdjustment
spec:
  name: Timestamp_Adjustment
  processors:
    - TimestampAdjustment
  sinks:
    - EventWatch
  router: SyslogRouter
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: TimestampAdjustment
spec:
  type: parser
  local: System_Timestamp_Adjustment
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: SyslogEndpoint
spec:
  type: syslog
  format: json
  router: SyslogRouter
  config:
    syslog:
      path: ""
