---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: CloudSyslog
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/fluency-collector-via-syslog-sq.png"
  category: system
  resourceGroups:
    - System
  description: "Syslog Endpoint on AWS Cloud for data import"
  displayName: "Cloud Syslog Endpoint"
---
apiVersion: application.ingext.io/v1
kind: Router
metadata:
  name: SyslogRouter
spec:
  threadCount: 1
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: Timestamp_Adjustment
spec:
  name: main
  processors:
    - TimestampAdjustment
  router: SyslogRouter
  priority: 100
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: TimestampAdjustment
spec:
  type: parser
  local: Timestamp_Adjustment
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: Syslog_Passthrough
spec:
  name: main
  processors:
    - SyslogPassthrough
  sinks:
    - EventWatch
  router: SyslogRouter
  priority: 30000
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: SyslogPassthrough
spec:
  type: parser
  local: Syslog_Passthrough
---
apiVersion: application.ingext.io/v1
kind: DataSource
metadata:
  name: SyslogEndpoint
spec:
  type: syslog
  format: json
  router: SyslogRouter
  config:
    syslog:
      path: "/var/log/remote"
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "EventWatch"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
