---
apiVersion: application.ingext.io/v1
kind: AppConfig
metadata:
  name: WindowsSrvNxLog
spec:
  icon: "https://fluency-public.s3.us-east-1.amazonaws.com/icons/windows-via-nxlog-syslog-sq.png"
  category: endpoint
  resourceGroups:
    - AD
  description: "Windows Server events via NXLog / Syslog"
  displayName: "Windows Server w/ NXLog"
  parameters:
---
apiVersion: application.ingext.io/v1
kind: Processor
metadata:
  name: WindowsSrv-NXLog
spec:
  type: parser
  local: WindowsSrv_NXLog
---
apiVersion: application.ingext.io/v1
kind: Pipe
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  name: main
  processors:
    - WindowsSrv-NXLog
  sinks:
    - "{{ .Application }}-{{ .AppInstance }}"
  router: SyslogRouter
  priority: 1000
---
apiVersion: application.ingext.io/v1
kind: DataSink
metadata:
  name: "{{ .Application }}-{{ .AppInstance }}"
spec:
  type: redis
  config:
    redis:
      queue: "queue:LVDBService:FileQueue"
