* Fluency_LavadbFpl(searchText)
** Search LavaDB in FPL1.0
----
let office_aad_by_ops_fpl = `
    search {from="{{.from}}", to="{{.to}}"} sContent("@sender","office365") and sContent("@source","Audit.AzureActiveDirectory")
    let { {{ .groupBy }}  } = f("@fields")
    aggregate events = count() by {{ .groupBy }}
    sort 15 events
`

let office_aad_by_ops = fluencyLavadbFpl(
     template(office_aad_by_ops_fpl, 
              {from:"-24h", to:"@h", groupBy: "Operation"}))

return {office_aad_by_ops}
----
* Fluency_LavadbQuery(query, options, ()=>{})
** Search LavaDB with Lucene query
** options: {from, to, dataType}
** from, to could be relative time "@h", "@m", "@d" or absolute time "2021-01-01T00:00:00Z", OR unix epoch time in millisecond
** dataType: "event" or "metaflow"
----
let hits = Fluency_LavadbQuery("", {from:"-4h@m", to:"@m"}, (obj) => {
   return {sender:obj["@sender"], source:obj["@source"]}
}) 
return {hits}
----
* Fluency_BehaviorSearch(query, from, to, ()=>{})
** Search Fluency Behavior Event database
* Fluency_SummarySearch(query, from, to, ()=>{})
** Search Fluency Behavior Summary database
----
function main() {
    let behaviorEvents = Fluency_BehaviorSearch("riskScore: [100 TO *]", "-10d@m", "@m", (obj) => {
       let {behaviorRule, behavior, riskScore, key } = obj
       return {behaviorRule, behavior, riskScore, key} 
    })
    let behaviorSummary = Fluency_SummarySearch("riskScore: [3000 TO *] AND NOT (status:new)", "-10d@m", "@m", (obj) => {
       let {id, behaviorRules, riskScore, key, dayIndex, status } = obj
       return {id, obj, behaviorRules, riskScore, key, dayIndex, status} 
    })
    
    return {behaviorEvents, behaviorSummary}
}
----
* Fluency_ResourceLoad(vendor, resource, customer, (obj <,customer>)=> {})
** vendor: Office365: resource: user, group, device, application, installedApp
** vendor Sentinelone: resource: agent, threat, application
** vendor AD: resource: user, asset
** vendor fehx (FireEyeHx):  resource: device
** vendor Qualys:  resource: host  
----
function main() {
  let users = Fluency_ResourceLoad("office365", "user", "*", (obj, customer) => {
      let fields = obj["@office365User"]
      let {userType, userPrincipalName, roles, accountEnabled, createdDateTime} = fields
      return {customer, userType, userPrincipalName, roles, accountEnabled, createdDateTime}
  })
  return {users}
}
----


* Fluency_FusionEvent(partition, source)
** Send Fusion Event to Fluency Fusion Service (legacy)
----
   let t = new Time()
   let partition={
      partition: "default",
      dataType: "event",
      time_ms: t.UnixMilli()
   }
   let source={
     logon: { 
      ip:"10.132.47.10",
      domain:"TERPLAB.COM",
      username:"foobar"
     },
     dtype:"windows-logon"
   } 
   Fluency_FusionEvent(partition, source)   

----


