AWSTemplateFormatVersion: "2010-09-09"
Description: Create S3 bucket for VPC flow logs.
Parameters:    
  S3Bucket: 
    Type: String
    Default: ingext-vpcflows

  SQSQueueName:
    Type: String
    Default: ingext-vpcflows-notify

  ExpirationInDays:
    Type: Number 
    Default: 10

Resources:
  BucketR:
    Type: AWS::S3::Bucket
    DependsOn:
      - SQSEventQueuePolicyR
    Properties:
      BucketName: !Ref S3Bucket
      LifecycleConfiguration:
        Rules:
          - Id: expire
            Status: Enabled
            ExpirationInDays: !Ref ExpirationInDays
      NotificationConfiguration:
        QueueConfigurations: 
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt SQSEventQueueR.Arn

  BucketPolicyR:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AWSLogDeliveryWrite
          Effect: Allow
          Principal:
            Service: delivery.logs.amazonaws.com
          Action: s3:PutObject
          Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
          Condition:
            StringEquals:
              'aws:SourceAccount': !Sub "${AWS::AccountId}"
              's3:x-amz-acl': bucket-owner-full-control
            ArnLike:
              'aws:SourceArn': !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - Sid: AWSLogDeliveryAclCheck
          Effect: Allow
          Principal:
            Service: delivery.logs.amazonaws.com  
          Action: s3:GetBucketAcl
          Resource: !Sub "arn:aws:s3:::${S3Bucket}"
          Condition:
            StringEquals:
              'aws:SourceAccount': !Sub "${AWS::AccountId}"
            ArnLike:
              'aws:SourceArn': !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  SQSEventQueueR:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SQSQueueName
    
  SQSEventQueuePolicyR:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: 
      - !Ref SQSEventQueueR
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: sqs:SendMessage
          Resource: !Sub "arn:aws:sqs:*:*:${SQSQueueName}"
          Condition:
            ArnEquals: 
              aws:SourceArn: !Sub "arn:aws:s3:::${S3Bucket}"


Outputs:
  QueueURL:
    Value: !Ref SQSEventQueueR
    Description: SQS Queue URL

  BucketARN: 
    Description: "ARN of new S3 bucket"
    Value: 
      Fn::GetAtt: 
        - BucketR
        - "Arn"
